// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvkyaclipubdubcodagr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2a3lhY2xpcHViZHViY29kYWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDU1MzEsImV4cCI6MjA2NDcyMTUzMX0.Qh0p_h4vcermDpBCLTmHp2tFPmPlParfdYpoU5iVSi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);